project:
  type: website

website:
  title: "분석하는 O2생활"
  site-url: "https://rmathematics-qmd.netlify.app/"
  description: "O2 생활 Qmd 블로그"
  navbar:
    search: true
    background: dark
    foreground: white
    highlight: link-color
    logo: ./img/logo.png
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - text: 'R 기초통계'
        file: docs/rstat101/index.qmd
      - text: 'About'
        file: about.qmd
      - text: 'Contact'
        file: contact.qmd
      - text: "Blog"
        href: docs/blog/index.qmd
      
    right: 
      - icon: github
        href: https://github.com/DataChuLee
        aria-label: Github Of DataChu
      - icon: rss
        href: docs/blog/index.xml
  sidebar:
    - title: "R 기초통계"
      style: "floating"
      collapse-level: 3
      align: left
      contents: 
        - docs/rstat101/index.qmd
        - docs/rstat101/lec1.qmd
        - docs/rstat101/lec2.qmd  
    - title: "Contact"
      contents: 
        - contact.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual