project:
  type: website

website:
  title: "분석하는 O2"
  site-url: "https://rmathematics-qmd.netlify.app/"
  description: "O2 Qmd 블로그"
  navbar:
    search: true
    logo: ./img/logo.png
    collapse-below: lg
    right:
      - text: 'R study'
        file: Rstudy.qmd
      - text: 'R tidyverse'
        file: Rtidyverse.qmd
      - text: 'About'
        file: about.qmd
      - text: "Blog"
        href: blog/index.qmd
      - icon: github
        href: https://github.com/DataChuLee
        aria-label: Github Of DataChu
      - icon: rss
        href: blog/index.xml
  comments: 
    hypothesis: 
      theme: clean
      openSidebar: false
format:
  html:
    smooth-scroll: true
    theme: 
      - styles.css
      - custom.scss
    toc: true
    toc-location: right
    code-link: true

editor: visual